/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import packagee.controller.AuthController;
import packagee.controller.ControllerResponse;
import packagee.controller.PatientController;
import packagee.repository.JsonUserRepository;
import packagee.repository.UserRepository;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class NewJFrame extends javax.swing.JFrame {

    private int x, y;
    private ArrayList<User> users;
    private ArrayList<Hospitalization> hospitalizations;
    private ArrayList<Appointment> appointments;
    private UserRepository userRepository;
    private AuthController authController;
    private PatientController patientController;

    public NewJFrame() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);

        this.userRepository = new JsonUserRepository("json/users.json");
        this.users = new ArrayList<>(userRepository.findAll());
        this.hospitalizations = new ArrayList<>();
        this.appointments = new ArrayList<>();
        this.authController = new AuthController(userRepository);
        this.patientController = new PatientController(userRepository);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new packagee.PanelRound();
        titleBarPanel = new packagee.PanelRound();
        closeButton = new javax.swing.JButton();
        authTabbedPane = new javax.swing.JTabbedPane();
        loginPanel = new packagee.PanelRound();
        loginTitleLabel = new javax.swing.JLabel();
        loginUsernameField = new javax.swing.JTextField();
        loginUsernameLabel = new javax.swing.JLabel();
        loginPasswordField = new javax.swing.JTextField();
        loginPasswordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        patientRegisterPanel = new javax.swing.JPanel();
        registerFirstnameLabel = new javax.swing.JLabel();
        registerPatientFirstnameField = new javax.swing.JTextField();
        registerLastnameLabel = new javax.swing.JLabel();
        registerPatientLastnameField = new javax.swing.JTextField();
        registerIdLabel = new javax.swing.JLabel();
        registerPatientIdField = new javax.swing.JTextField();
        registerGenderLabel = new javax.swing.JLabel();
        registerPhoneLabel = new javax.swing.JLabel();
        registerPatientPhoneField = new javax.swing.JTextField();
        registerEmailLabel = new javax.swing.JLabel();
        registerPatientEmailField = new javax.swing.JTextField();
        registerUsernameLabel = new javax.swing.JLabel();
        registerPatientUsernameField = new javax.swing.JTextField();
        registerPatientPasswordField = new javax.swing.JTextField();
        registerPasswordLabel = new javax.swing.JLabel();
        registerConfirmPasswordLabel = new javax.swing.JLabel();
        registerPatientConfirmPasswordField = new javax.swing.JTextField();
        registerPatientGenderComboBox = new javax.swing.JComboBox<>();
        registerPatientButton = new javax.swing.JButton();
        registerAddressLabel = new javax.swing.JLabel();
        registerPatientAddressField = new javax.swing.JTextField();
        registerBirthdateLabel = new javax.swing.JLabel();
        registerPatientBirthdateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setRadius(50);

        titleBarPanel.setRadius(50);
        titleBarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarPanelMouseDragged(evt);
            }
        });
        titleBarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarPanelMousePressed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        closeButton.setText("X");
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        closeButton.setFocusable(false);
        closeButton.setRequestFocusEnabled(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(titleBarPanel);
        titleBarPanel.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        loginTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        loginTitleLabel.setText("LOGIN");

        loginUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginUsernameField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        loginUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginUsernameLabel.setText("USERNAME");

        loginPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginPasswordField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        loginPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginPasswordLabel.setText("PASSWORD");

        loginButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginButton.setText("ENTER");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(loginTitleLabel)
                .addGap(481, 481, 481))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginPasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(loginUsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(loginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(loginButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(loginTitleLabel)
                .addGap(74, 74, 74)
                .addComponent(loginUsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(loginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(loginButton)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        authTabbedPane.addTab("Login", loginPanel);

        registerFirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerFirstnameLabel.setText("Firstname");

        registerPatientFirstnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerLastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerLastnameLabel.setText("Lastname");

        registerPatientLastnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerIdLabel.setText("ID");

        registerPatientIdField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerGenderLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerGenderLabel.setText("Gender");

        registerPhoneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPhoneLabel.setText("Phone");

        registerPatientPhoneField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerEmailLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerEmailLabel.setText("Email");

        registerPatientEmailField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerUsernameLabel.setText("User");

        registerPatientUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerPatientPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPasswordLabel.setText("Password");

        registerConfirmPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerConfirmPasswordLabel.setText("Password confirmation");

        registerPatientConfirmPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientConfirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPatientConfirmPasswordFieldActionPerformed(evt);
            }
        });

        registerPatientGenderComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        registerPatientButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientButton.setText("Save");
        registerPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPatientButtonActionPerformed(evt);
            }
        });

        registerAddressLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerAddressLabel.setText("Address");

        registerPatientAddressField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerBirthdateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerBirthdateLabel.setText("Birthdate");

        registerPatientBirthdateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(patientRegisterPanel);
        patientRegisterPanel.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(registerPasswordLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerPatientUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerPatientPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(registerUsernameLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(registerPatientConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(registerPatientButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(registerConfirmPasswordLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(registerBirthdateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerPatientBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(registerFirstnameLabel)
                                .addGap(34, 34, 34)
                                .addComponent(registerPatientFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerLastnameLabel)
                            .addComponent(registerAddressLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(registerPatientLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerIdLabel)
                                .addGap(30, 30, 30)
                                .addComponent(registerPatientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerGenderLabel)
                                .addGap(26, 26, 26)
                                .addComponent(registerPatientGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(registerPatientAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerPhoneLabel)
                                .addGap(18, 18, 18)
                                .addComponent(registerPatientPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerEmailLabel)
                                .addGap(18, 18, 18)
                                .addComponent(registerPatientEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerFirstnameLabel)
                    .addComponent(registerPatientFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerLastnameLabel)
                    .addComponent(registerPatientLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerIdLabel)
                    .addComponent(registerPatientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerGenderLabel)
                    .addComponent(registerPatientGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(registerBirthdateLabel)
                        .addComponent(registerPatientBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(registerAddressLabel)
                        .addComponent(registerPatientAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(registerPhoneLabel)
                        .addComponent(registerPatientPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(registerEmailLabel)
                        .addComponent(registerPatientEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(registerUsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(registerPatientUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(registerPatientPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerConfirmPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(registerPatientConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(registerPatientButton)
                .addGap(42, 42, 42))
        );

        authTabbedPane.addTab("Patient register", patientRegisterPanel);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(authTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(titleBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authTabbedPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleBarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void titleBarPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ControllerResponse response = authController.login(loginUsernameField.getText(), loginPasswordField.getText());
        if (!response.isOk()) {
            JOptionPane.showMessageDialog(this, response.getMessage());
            return;
        }

        User selectedUser = authController.getUserByUsername(loginUsernameField.getText());
        if (selectedUser instanceof Administrator) {
            NewJFrame11 admin = new NewJFrame11(selectedUser, users, hospitalizations, appointments);
            this.setVisible(false);
            admin.setVisible(true);
        } else if (selectedUser instanceof Doctor) {
            NewJFrame111 doctor = new NewJFrame111(selectedUser, (Doctor) selectedUser, users, hospitalizations, appointments);
            this.setVisible(false);
            doctor.setVisible(true);
        } else {
            NewJFrame1 patient = new NewJFrame1(selectedUser, (Patient) selectedUser, users, appointments, hospitalizations);
            this.setVisible(false);
            patient.setVisible(true);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void registerPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ControllerResponse response = patientController.registerPatient(
                registerPatientFirstnameField.getText(),
                registerPatientLastnameField.getText(),
                registerPatientIdField.getText(),
                String.valueOf(registerPatientGenderComboBox.getSelectedItem()),
                registerPatientBirthdateField.getText(),
                registerPatientAddressField.getText(),
                registerPatientPhoneField.getText(),
                registerPatientEmailField.getText(),
                registerPatientUsernameField.getText(),
                registerPatientPasswordField.getText(),
                registerPatientConfirmPasswordField.getText()
        );

        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            users.clear();
            users.addAll(userRepository.findAll());
            clearPatientForm();
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void registerPatientConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void clearPatientForm() {
        registerPatientFirstnameField.setText("");
        registerPatientLastnameField.setText("");
        registerPatientIdField.setText("");
        registerPatientGenderComboBox.setSelectedIndex(0);
        registerPatientBirthdateField.setText("");
        registerPatientAddressField.setText("");
        registerPatientPhoneField.setText("");
        registerPatientEmailField.setText("");
        registerPatientUsernameField.setText("");
        registerPatientPasswordField.setText("");
        registerPatientConfirmPasswordField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton registerPatientButton;
    private javax.swing.JComboBox<String> registerPatientGenderComboBox;
    private javax.swing.JLabel loginTitleLabel;
    private javax.swing.JLabel registerUsernameLabel;
    private javax.swing.JLabel registerPasswordLabel;
    private javax.swing.JLabel registerConfirmPasswordLabel;
    private javax.swing.JLabel registerAddressLabel;
    private javax.swing.JLabel registerBirthdateLabel;
    private javax.swing.JLabel loginUsernameLabel;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JLabel registerFirstnameLabel;
    private javax.swing.JLabel registerLastnameLabel;
    private javax.swing.JLabel registerIdLabel;
    private javax.swing.JLabel registerGenderLabel;
    private javax.swing.JLabel registerPhoneLabel;
    private javax.swing.JLabel registerEmailLabel;
    private javax.swing.JPanel patientRegisterPanel;
    private javax.swing.JTabbedPane authTabbedPane;
    private javax.swing.JTextField loginUsernameField;
    private javax.swing.JTextField registerPatientConfirmPasswordField;
    private javax.swing.JTextField registerPatientAddressField;
    private javax.swing.JTextField registerPatientBirthdateField;
    private javax.swing.JTextField loginPasswordField;
    private javax.swing.JTextField registerPatientFirstnameField;
    private javax.swing.JTextField registerPatientLastnameField;
    private javax.swing.JTextField registerPatientIdField;
    private javax.swing.JTextField registerPatientPhoneField;
    private javax.swing.JTextField registerPatientEmailField;
    private javax.swing.JTextField registerPatientUsernameField;
    private javax.swing.JTextField registerPatientPasswordField;
    private packagee.PanelRound mainPanel;
    private packagee.PanelRound titleBarPanel;
    private packagee.PanelRound loginPanel;
    // End of variables declaration//GEN-END:variables
}
