/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;
import packagee.Factory.AppointmentIdFactory;
import packagee.controller.AppointmentController;
import packagee.controller.ControllerResponse;
import packagee.controller.HospitalizationController;
import packagee.controller.PatientController;
import packagee.repository.AppointmentRepository;
import packagee.repository.HospitalizationRepository;
import packagee.repository.ListAppointmentRepository;
import packagee.repository.ListHospitalizationRepository;
import packagee.repository.ListUserRepository;
import packagee.repository.UserRepository;
import packagee.observer.DataObserver;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class NewJFrame1 extends javax.swing.JFrame {

    private int x, y;
    private User user;
    private ArrayList<User> users;
    private Patient patient;
    private ArrayList<Appointment> appointments;
    private ArrayList<Hospitalization> hospitalizations;
    private UserRepository userRepository;
    private AppointmentRepository appointmentRepository;
    private HospitalizationRepository hospitalizationRepository;
    private PatientController patientController;
    private AppointmentController appointmentController;
    private HospitalizationController hospitalizationController;

    public NewJFrame1(User user,Patient patient, ArrayList<User> users, ArrayList<Appointment>appointments, ArrayList<Hospitalization> hospitalizations) {
        initComponents();
        this.user = user;
        this.users = users;
        this.patient = patient;
        this.hospitalizations = hospitalizations;
        this.appointments = appointments;
        this.userRepository = new ListUserRepository(users);
        this.appointmentRepository = new ListAppointmentRepository(appointments);
        this.hospitalizationRepository = new ListHospitalizationRepository(hospitalizations);
        this.patientController = new PatientController(userRepository);
        this.appointmentController = new AppointmentController(appointmentRepository, userRepository, new AppointmentIdFactory(appointmentRepository));
        this.hospitalizationController = new HospitalizationController(hospitalizationRepository, userRepository);
        this.appointmentRepository.addObserver(new DataObserver() {
            @Override
            public void update() {
                loadPatientCombos();
                loadAppointmentTable();
            }
        });
        this.hospitalizationRepository.addObserver(new DataObserver() {
            @Override
            public void update() {
                loadPatientCombos();
            }
        });
        this.userRepository.addObserver(new DataObserver() {
            @Override
            public void update() {
                loadPatientCombos();
            }
        });
        if (user instanceof Administrator) {
            backToAdminButton.setVisible(true);
        } else {
            backToAdminButton.setVisible(false);
        }
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        loadPatientData();
        loadPatientCombos();
        loadAppointmentTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new packagee.PanelRound();
        titleBarPanel = new packagee.PanelRound();
        closeButton = new javax.swing.JButton();
        patientViewTitleLabel = new javax.swing.JLabel();
        backToAdminButton = new javax.swing.JButton();
        patientTabbedPane = new javax.swing.JTabbedPane();
        appointmentRequestPanel = new javax.swing.JPanel();
        appointmentTableScrollPane = new javax.swing.JScrollPane();
        patientAppointmentsTable = new javax.swing.JTable();
        refreshAppointmentsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        appointmentsPanel = new javax.swing.JPanel();
        patientFirstnameLabel = new javax.swing.JLabel();
        patientFirstnameField = new javax.swing.JTextField();
        patientLastnameLabel = new javax.swing.JLabel();
        patientLastnameField = new javax.swing.JTextField();
        patientBirthdateLabel = new javax.swing.JLabel();
        patientBirthdateField = new javax.swing.JTextField();
        patientGenderLabel = new javax.swing.JLabel();
        patientEmailLabel = new javax.swing.JLabel();
        patientEmailField = new javax.swing.JTextField();
        patientPhoneLabel = new javax.swing.JLabel();
        patientPhoneField = new javax.swing.JTextField();
        patientAddressLabel = new javax.swing.JLabel();
        patientAddressField = new javax.swing.JTextField();
        patientPasswordField = new javax.swing.JTextField();
        patientPasswordLabel = new javax.swing.JLabel();
        patientConfirmPasswordLabel = new javax.swing.JLabel();
        patientConfirmPasswordField = new javax.swing.JTextField();
        savePatientButton = new javax.swing.JButton();
        patientUsernameLabel = new javax.swing.JLabel();
        patientUsernameField = new javax.swing.JTextField();
        patientGenderComboBox = new javax.swing.JComboBox<>();
        patientProfilePanel = new javax.swing.JPanel();
        appointmentRequestTitleLabel = new javax.swing.JLabel();
        searchBySpecialtyRadioButton = new javax.swing.JRadioButton();
        searchByDoctorRadioButton = new javax.swing.JRadioButton();
        patientHeaderSeparator = new javax.swing.JSeparator();
        appointmentDateLabel = new javax.swing.JLabel();
        appointmentDateField = new javax.swing.JTextField();
        appointmentTimeField = new javax.swing.JTextField();
        appointmentTimeLabel = new javax.swing.JLabel();
        appointmentTypeLabel = new javax.swing.JLabel();
        appointmentReasonLabel = new javax.swing.JLabel();
        appointmentTypeComboBox = new javax.swing.JComboBox<>();
        createAppointmentButton = new javax.swing.JButton();
        patientFormSeparator = new javax.swing.JSeparator();
        hospitalizationRequestTitleLabel = new javax.swing.JLabel();
        hospitalizationReasonLabel = new javax.swing.JLabel();
        hospitalizationDoctorLabel = new javax.swing.JLabel();
        hospitalizationDoctorComboBox = new javax.swing.JComboBox<>();
        hospitalizationDateField = new javax.swing.JTextField();
        hospitalizationDateLabel = new javax.swing.JLabel();
        roomTypeLabel = new javax.swing.JLabel();
        roomTypeComboBox = new javax.swing.JComboBox<>();
        hospitalizationObservationsLabel = new javax.swing.JLabel();
        appointmentsScrollPane = new javax.swing.JScrollPane();
        hospitalizationObservationsArea = new javax.swing.JTextArea();
        requestHospitalizationButton = new javax.swing.JButton();
        cancelAppointmentTitleLabel = new javax.swing.JLabel();
        cancelAppointmentIdLabel = new javax.swing.JLabel();
        cancelAppointmentObservationsLabel = new javax.swing.JLabel();
        hospitalizationObservationsScrollPane = new javax.swing.JScrollPane();
        cancelAppointmentObservationsArea = new javax.swing.JTextArea();
        cancelAppointmentButton = new javax.swing.JButton();
        cancelObservationsScrollPane = new javax.swing.JScrollPane();
        hospitalizationReasonArea = new javax.swing.JTextArea();
        appointmentReasonScrollPane = new javax.swing.JScrollPane();
        appointmentReasonArea = new javax.swing.JTextArea();
        cancelAppointmentComboBox = new javax.swing.JComboBox<>();
        doctorOrSpecialtyComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setRadius(50);

        titleBarPanel.setRadius(50);
        titleBarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarPanelMouseDragged(evt);
            }
        });
        titleBarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarPanelMousePressed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        closeButton.setText("X");
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        closeButton.setFocusable(false);
        closeButton.setRequestFocusEnabled(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        patientViewTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        patientViewTitleLabel.setText("PATIENT VIEW");

        backToAdminButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        backToAdminButton.setText("Back");
        backToAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToAdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(titleBarPanel);
        titleBarPanel.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(patientViewTitleLabel)
                .addGap(29, 29, 29)
                .addComponent(backToAdminButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeButton))
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backToAdminButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(patientViewTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        patientAppointmentsTable.setAutoCreateRowSorter(true);
        patientAppointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        appointmentTableScrollPane.setViewportView(patientAppointmentsTable);

        refreshAppointmentsButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        refreshAppointmentsButton.setText("Refresh");
        refreshAppointmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAppointmentsButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(appointmentRequestPanel);
        appointmentRequestPanel.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(appointmentTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(refreshAppointmentsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(78, 78, 78))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(appointmentTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshAppointmentsButton)
                    .addComponent(logoutButton))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        patientTabbedPane.addTab("Appointment history", appointmentRequestPanel);

        patientFirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientFirstnameLabel.setText("Firstname");

        patientFirstnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientLastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientLastnameLabel.setText("Lastname");

        patientLastnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientBirthdateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientBirthdateLabel.setText("Birthdate");

        patientBirthdateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientGenderLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientGenderLabel.setText("Gender");

        patientEmailLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientEmailLabel.setText("Email");

        patientEmailField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientPhoneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientPhoneLabel.setText("Phone");

        patientPhoneField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientAddressLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientAddressLabel.setText("Address");

        patientAddressField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientPasswordLabel.setText("Password");

        patientConfirmPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientConfirmPasswordLabel.setText("Password confirmation");

        patientConfirmPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        savePatientButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        savePatientButton.setText("Save");
        savePatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePatientButtonActionPerformed(evt);
            }
        });

        patientUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientUsernameLabel.setText("User");

        patientUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientGenderComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(appointmentsPanel);
        appointmentsPanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(patientFirstnameLabel)
                .addGap(18, 18, 18)
                .addComponent(patientFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(patientLastnameLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(patientPhoneLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(patientAddressLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(patientLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(patientBirthdateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(patientGenderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(patientEmailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(patientEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(savePatientButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(patientConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(patientConfirmPasswordLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(patientPasswordLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(patientUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(patientUsernameLabel)))
                            .addComponent(patientPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientFirstnameLabel)
                    .addComponent(patientFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientLastnameLabel)
                    .addComponent(patientLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientBirthdateLabel)
                    .addComponent(patientBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientGenderLabel)
                    .addComponent(patientEmailLabel)
                    .addComponent(patientEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientPhoneLabel)
                    .addComponent(patientPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientAddressLabel)
                    .addComponent(patientAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(patientUsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(patientUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(patientPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(patientPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(patientConfirmPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(patientConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(savePatientButton)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        patientTabbedPane.addTab("Modify info", appointmentsPanel);

        appointmentRequestTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentRequestTitleLabel.setText("Request medical appointment");

        searchBySpecialtyRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        searchBySpecialtyRadioButton.setText("Specialty");
        searchBySpecialtyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBySpecialtyRadioButtonActionPerformed(evt);
            }
        });

        searchByDoctorRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        searchByDoctorRadioButton.setText("Doctor");
        searchByDoctorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByDoctorRadioButtonActionPerformed(evt);
            }
        });

        patientHeaderSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        appointmentDateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentDateLabel.setText("Appointment date");

        appointmentDateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        appointmentTimeField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        appointmentTimeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentTimeLabel.setText("Appointment time");

        appointmentTypeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentTypeLabel.setText("Appointment type");

        appointmentReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentReasonLabel.setText("Appointment reason");

        appointmentTypeComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Remote", "In-person" }));

        createAppointmentButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        createAppointmentButton.setText("Create");
        createAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAppointmentButtonActionPerformed(evt);
            }
        });

        patientFormSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        hospitalizationRequestTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationRequestTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationRequestTitleLabel.setText("Request hospitalization");

        hospitalizationReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationReasonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationReasonLabel.setText("Hospitalization reason");

        hospitalizationDoctorLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationDoctorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationDoctorLabel.setText("Attending doctor");

        hospitalizationDoctorComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationDoctorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        hospitalizationDateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        hospitalizationDateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationDateLabel.setText("Estimated date of admission");
        hospitalizationDateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        roomTypeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        roomTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomTypeLabel.setText("Desired room type");

        roomTypeComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        roomTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        hospitalizationObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationObservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationObservationsLabel.setText("Observations");

        hospitalizationObservationsArea.setColumns(20);
        hospitalizationObservationsArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationObservationsArea.setRows(5);
        appointmentsScrollPane.setViewportView(hospitalizationObservationsArea);

        requestHospitalizationButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        requestHospitalizationButton.setText("Create");
        requestHospitalizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestHospitalizationButtonActionPerformed(evt);
            }
        });

        cancelAppointmentTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelAppointmentTitleLabel.setText("Cancel appointment");

        cancelAppointmentIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelAppointmentIdLabel.setText("ID appointment");

        cancelAppointmentObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelAppointmentObservationsLabel.setText("Observations");

        cancelAppointmentObservationsArea.setColumns(20);
        cancelAppointmentObservationsArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelAppointmentObservationsArea.setRows(5);
        hospitalizationObservationsScrollPane.setViewportView(cancelAppointmentObservationsArea);

        cancelAppointmentButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelAppointmentButton.setText("Cancel");
        cancelAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAppointmentButtonActionPerformed(evt);
            }
        });

        hospitalizationReasonArea.setColumns(20);
        hospitalizationReasonArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationReasonArea.setRows(5);
        cancelObservationsScrollPane.setViewportView(hospitalizationReasonArea);

        appointmentReasonArea.setColumns(20);
        appointmentReasonArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentReasonArea.setRows(5);
        appointmentReasonScrollPane.setViewportView(appointmentReasonArea);

        cancelAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        doctorOrSpecialtyComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorOrSpecialtyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(patientProfilePanel);
        patientProfilePanel.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(searchBySpecialtyRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchByDoctorRadioButton))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(appointmentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(appointmentTimeLabel)
                                        .addComponent(appointmentDateLabel)
                                        .addComponent(doctorOrSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(appointmentTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(appointmentReasonLabel))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(appointmentTypeLabel))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(appointmentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(appointmentRequestTitleLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(appointmentReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(createAppointmentButton)))
                .addGap(69, 69, 69)
                .addComponent(patientHeaderSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addComponent(requestHospitalizationButton))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hospitalizationReasonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelObservationsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(hospitalizationRequestTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(hospitalizationDoctorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hospitalizationObservationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hospitalizationDateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(appointmentsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roomTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(hospitalizationDoctorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(hospitalizationDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(roomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(patientFormSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospitalizationObservationsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(cancelAppointmentTitleLabel))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(cancelAppointmentButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cancelAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cancelAppointmentIdLabel)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(cancelAppointmentObservationsLabel)))
                        .addGap(49, 49, 49)))
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientHeaderSeparator)
            .addComponent(patientFormSeparator)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hospitalizationRequestTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(hospitalizationReasonLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hospitalizationDoctorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(hospitalizationDoctorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hospitalizationDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hospitalizationDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(roomTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(roomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hospitalizationObservationsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(appointmentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(requestHospitalizationButton)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(appointmentRequestTitleLabel)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(searchBySpecialtyRadioButton)
                                    .addComponent(searchByDoctorRadioButton))
                                .addGap(18, 18, 18)
                                .addComponent(doctorOrSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(appointmentDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(appointmentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(appointmentTimeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(appointmentTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(appointmentReasonLabel)
                                .addGap(24, 24, 24)
                                .addComponent(appointmentReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cancelAppointmentTitleLabel)
                                .addGap(39, 39, 39)
                                .addComponent(cancelAppointmentIdLabel)
                                .addGap(18, 18, 18)
                                .addComponent(cancelAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelAppointmentObservationsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(hospitalizationObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(cancelAppointmentButton)))
                        .addGap(18, 18, 18)
                        .addComponent(appointmentTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(appointmentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(createAppointmentButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        patientTabbedPane.addTab("Request/Cancel", patientProfilePanel);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(patientTabbedPane)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(titleBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientTabbedPane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleBarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void titleBarPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ControllerResponse response = appointmentController.cancelAppointment(String.valueOf(cancelAppointmentComboBox.getSelectedItem()));
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            loadPatientCombos();
            loadAppointmentTable();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void savePatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ControllerResponse response = patientController.updatePatient(
                String.valueOf(patient.getId()),
                patientFirstnameField.getText(),
                patientLastnameField.getText(),
                String.valueOf(patientGenderComboBox.getSelectedItem()),
                patientBirthdateField.getText(),
                patientAddressField.getText(),
                patientPhoneField.getText(),
                patientEmailField.getText(),
                patientUsernameField.getText(),
                patientPasswordField.getText(),
                patientConfirmPasswordField.getText()
        );

        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            this.patient = (Patient) userRepository.findById(patient.getId());
            loadPatientData();
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        NewJFrame login = new NewJFrame();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void backToAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        NewJFrame11 admin = new NewJFrame11(user, users,hospitalizations, appointments);
        this.setVisible(false);
        admin.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void searchBySpecialtyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if (searchByDoctorRadioButton.isSelected()) {
            searchByDoctorRadioButton.setSelected(false);
        }

        doctorOrSpecialtyComboBox.removeAllItems();

        doctorOrSpecialtyComboBox.addItem("Select one");
        for (Specialty spec : Specialty.values()) {
            doctorOrSpecialtyComboBox.addItem(spec.toDisplayString());
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void searchByDoctorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        if (searchBySpecialtyRadioButton.isSelected()) {
            searchBySpecialtyRadioButton.setSelected(false);
        }
        doctorOrSpecialtyComboBox.removeAllItems();

        doctorOrSpecialtyComboBox.addItem("Select one");
        for (User doc : this.users) {
            if (doc instanceof Doctor) {
                doctorOrSpecialtyComboBox.addItem(String.valueOf(doc.getId()));
            }
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void createAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String selectedValue = String.valueOf(doctorOrSpecialtyComboBox.getSelectedItem());
        String doctorId = searchByDoctorRadioButton.isSelected() ? selectedValue : "";
        String specialty = searchBySpecialtyRadioButton.isSelected() ? selectedValue : "";

        ControllerResponse response = appointmentController.requestAppointment(
                String.valueOf(patient.getId()),
                doctorId,
                specialty,
                appointmentDateField.getText(),
                appointmentTimeField.getText(),
                appointmentReasonArea.getText(),
                String.valueOf(appointmentTypeComboBox.getSelectedItem())
        );

        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            clearAppointmentForm();
            loadPatientCombos();
            loadAppointmentTable();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    private void refreshAppointmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        loadAppointmentTable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void requestHospitalizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ControllerResponse response = hospitalizationController.requestHospitalization(
                String.valueOf(patient.getId()),
                String.valueOf(hospitalizationDoctorComboBox.getSelectedItem()),
                hospitalizationDateField.getText(),
                hospitalizationReasonArea.getText(),
                String.valueOf(roomTypeComboBox.getSelectedItem()),
                hospitalizationObservationsArea.getText()
        );

        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            loadPatientCombos();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void loadPatientCombos() {
        hospitalizationDoctorComboBox.removeAllItems();
        hospitalizationDoctorComboBox.addItem("Select one");
        for (User currentUser : users) {
            if (currentUser instanceof Doctor) {
                hospitalizationDoctorComboBox.addItem(String.valueOf(currentUser.getId()));
            }
        }

        roomTypeComboBox.removeAllItems();
        roomTypeComboBox.addItem("Select one");
        for (RoomType roomType : RoomType.values()) {
            roomTypeComboBox.addItem(roomType.name());
        }

        cancelAppointmentComboBox.removeAllItems();
        cancelAppointmentComboBox.addItem("Select one");
        for (Appointment appointment : appointmentRepository.findByPatientId(patient.getId())) {
            if (appointment.getStatus() != AppointmentStatus.CANCELED && appointment.getStatus() != AppointmentStatus.COMPLETED) {
                cancelAppointmentComboBox.addItem(appointment.getId());
            }
        }
    }

    private void loadPatientData() {
        patientFirstnameField.setText(patient.getFirstname());
        patientLastnameField.setText(patient.getLastname());
        patientGenderComboBox.setSelectedItem(patient.isGender() ? "Female" : "Male");
        patientBirthdateField.setText(patient.getBirthdate().toString());
        patientAddressField.setText(patient.getAddress());
        patientPhoneField.setText(String.valueOf(patient.getPhone()));
        patientEmailField.setText(patient.getEmail());
        patientUsernameField.setText(patient.getUsername());
        patientPasswordField.setText(patient.getPassword());
        patientConfirmPasswordField.setText(patient.getPassword());
    }

    private void loadAppointmentTable() {
        ControllerResponse response = appointmentController.listPatientAppointments(String.valueOf(patient.getId()));
        DefaultTableModel model = (DefaultTableModel) patientAppointmentsTable.getModel();
        model.setRowCount(0);
        if (!response.isOk()) {
            return;
        }

        JSONArray array = new JSONArray(response.getData());
        for (int i = 0; i < array.length(); i++) {
            JSONObject item = array.getJSONObject(i);
            model.addRow(new Object[]{
                item.getString("id"),
                item.getString("datetime"),
                item.getString("doctorName"),
                item.getString("specialty"),
                item.getString("type"),
                item.getString("status")
            });
        }
    }

    private void clearAppointmentForm() {
        searchBySpecialtyRadioButton.setSelected(false);
        searchByDoctorRadioButton.setSelected(false);
        doctorOrSpecialtyComboBox.removeAllItems();
        doctorOrSpecialtyComboBox.addItem("Select one");
        appointmentDateField.setText("");
        appointmentTimeField.setText("");
        appointmentTypeComboBox.setSelectedIndex(0);
        appointmentReasonArea.setText("");
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton createAppointmentButton;
    private javax.swing.JButton requestHospitalizationButton;
    private javax.swing.JButton cancelAppointmentButton;
    private javax.swing.JButton refreshAppointmentsButton;
    private javax.swing.JButton backToAdminButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton savePatientButton;
    private javax.swing.JComboBox<String> appointmentTypeComboBox;
    private javax.swing.JComboBox<String> hospitalizationDoctorComboBox;
    private javax.swing.JComboBox<String> roomTypeComboBox;
    private javax.swing.JComboBox<String> cancelAppointmentComboBox;
    private javax.swing.JComboBox<String> doctorOrSpecialtyComboBox;
    private javax.swing.JComboBox<String> patientGenderComboBox;
    private javax.swing.JLabel patientViewTitleLabel;
    private javax.swing.JLabel patientPasswordLabel;
    private javax.swing.JLabel patientConfirmPasswordLabel;
    private javax.swing.JLabel patientUsernameLabel;
    private javax.swing.JLabel appointmentRequestTitleLabel;
    private javax.swing.JLabel appointmentDateLabel;
    private javax.swing.JLabel appointmentTimeLabel;
    private javax.swing.JLabel appointmentTypeLabel;
    private javax.swing.JLabel appointmentReasonLabel;
    private javax.swing.JLabel hospitalizationRequestTitleLabel;
    private javax.swing.JLabel hospitalizationReasonLabel;
    private javax.swing.JLabel patientFirstnameLabel;
    private javax.swing.JLabel hospitalizationDoctorLabel;
    private javax.swing.JLabel hospitalizationDateLabel;
    private javax.swing.JLabel roomTypeLabel;
    private javax.swing.JLabel hospitalizationObservationsLabel;
    private javax.swing.JLabel cancelAppointmentTitleLabel;
    private javax.swing.JLabel cancelAppointmentIdLabel;
    private javax.swing.JLabel cancelAppointmentObservationsLabel;
    private javax.swing.JLabel patientLastnameLabel;
    private javax.swing.JLabel patientBirthdateLabel;
    private javax.swing.JLabel patientGenderLabel;
    private javax.swing.JLabel patientEmailLabel;
    private javax.swing.JLabel patientPhoneLabel;
    private javax.swing.JLabel patientAddressLabel;
    private javax.swing.JPanel appointmentsPanel;
    private javax.swing.JPanel patientProfilePanel;
    private javax.swing.JPanel appointmentRequestPanel;
    private javax.swing.JRadioButton searchBySpecialtyRadioButton;
    private javax.swing.JRadioButton searchByDoctorRadioButton;
    private javax.swing.JScrollPane appointmentsScrollPane;
    private javax.swing.JScrollPane hospitalizationObservationsScrollPane;
    private javax.swing.JScrollPane appointmentTableScrollPane;
    private javax.swing.JScrollPane cancelObservationsScrollPane;
    private javax.swing.JScrollPane appointmentReasonScrollPane;
    private javax.swing.JSeparator patientHeaderSeparator;
    private javax.swing.JSeparator patientFormSeparator;
    private javax.swing.JTabbedPane patientTabbedPane;
    private javax.swing.JTable patientAppointmentsTable;
    private javax.swing.JTextArea hospitalizationObservationsArea;
    private javax.swing.JTextArea cancelAppointmentObservationsArea;
    private javax.swing.JTextArea hospitalizationReasonArea;
    private javax.swing.JTextArea appointmentReasonArea;
    private javax.swing.JTextField patientFirstnameField;
    private javax.swing.JTextField patientConfirmPasswordField;
    private javax.swing.JTextField patientUsernameField;
    private javax.swing.JTextField appointmentDateField;
    private javax.swing.JTextField appointmentTimeField;
    private javax.swing.JTextField hospitalizationDateField;
    private javax.swing.JTextField patientLastnameField;
    private javax.swing.JTextField patientBirthdateField;
    private javax.swing.JTextField patientEmailField;
    private javax.swing.JTextField patientPhoneField;
    private javax.swing.JTextField patientAddressField;
    private javax.swing.JTextField patientPasswordField;
    private packagee.PanelRound mainPanel;
    private packagee.PanelRound titleBarPanel;
    // End of variables declaration//GEN-END:variables
}
