/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;
import packagee.Factory.AppointmentIdFactory;
import packagee.controller.AppointmentController;
import packagee.controller.ControllerResponse;
import packagee.controller.DoctorController;
import packagee.controller.HospitalizationController;
import packagee.controller.PrescriptionController;
import packagee.facade.OspedaleFacade;
import packagee.repository.AppointmentRepository;
import packagee.repository.HospitalizationRepository;
import packagee.repository.ListAppointmentRepository;
import packagee.repository.ListHospitalizationRepository;
import packagee.repository.ListUserRepository;
import packagee.repository.UserRepository;
import packagee.observer.DataObserver;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class NewJFrame111 extends javax.swing.JFrame {

    private int x, y;
    private User user;
    private ArrayList<User> users;
    private ArrayList<Hospitalization>hospitalizations;
    private ArrayList<Appointment>appointments;
    private Doctor doctor;
    private Patient patient;
    private UserRepository userRepository;
    private AppointmentRepository appointmentRepository;
    private HospitalizationRepository hospitalizationRepository;
    private AppointmentController appointmentController;
    private DoctorController doctorController;
    private HospitalizationController hospitalizationController;
    private PrescriptionController prescriptionController;
    private OspedaleFacade ospedaleFacade;

    public NewJFrame111(User user,Doctor doc, ArrayList<User> users,ArrayList<Hospitalization> hospitalizations,ArrayList<Appointment> appointments) {
        initComponents();
        this.user = user;
        this.users =users;
        this.doctor = doc;
        this.hospitalizations = hospitalizations;
        this.appointments = appointments;
        this.userRepository = new ListUserRepository(users);
        this.appointmentRepository = new ListAppointmentRepository(appointments);
        this.hospitalizationRepository = new ListHospitalizationRepository(hospitalizations);
        this.appointmentController = new AppointmentController(appointmentRepository, userRepository, new AppointmentIdFactory(appointmentRepository));
        this.doctorController = new DoctorController(userRepository);
        this.hospitalizationController = new HospitalizationController(hospitalizationRepository, userRepository, appointmentRepository);
        this.prescriptionController = new PrescriptionController();
        this.ospedaleFacade = new OspedaleFacade(appointmentController, hospitalizationController, prescriptionController);
        this.appointmentRepository.addObserver(new DataObserver() {
            @Override
            public void update() {
                loadDoctorCombos();
                loadDoctorAppointmentTable(pendingAppointmentsRadioButton.isSelected());
            }
        });
        this.hospitalizationRepository.addObserver(new DataObserver() {
            @Override
            public void update() {
                loadDoctorCombos();
            }
        });
        this.userRepository.addObserver(new DataObserver() {
            @Override
            public void update() {
                loadDoctorCombos();
            }
        });
        if (user instanceof Administrator)
            backToAdminButton.setVisible(true);
        else    
            backToAdminButton.setVisible(false);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        applyHospitalizationButton.setText("Apply");
        hospitalizationRequestsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalizationPatientIdRadioButton.setSelected(false);
                loadDoctorCombos();
            }
        });
        hospitalizationPatientIdRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalizationRequestsRadioButton.setSelected(false);
                loadDoctorCombos();
            }
        });
        loadDoctorData();
        loadDoctorCombos();
        loadDoctorAppointmentTable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new packagee.PanelRound();
        titleBarPanel = new packagee.PanelRound();
        closeButton = new javax.swing.JButton();
        doctorViewTitleLabel = new javax.swing.JLabel();
        backToAdminButton = new javax.swing.JButton();
        doctorTabbedPane = new javax.swing.JTabbedPane();
        hospitalizationsPanel = new javax.swing.JPanel();
        totalAppointmentsRadioButton = new javax.swing.JRadioButton();
        patientAppointmentsScrollPane = new javax.swing.JScrollPane();
        doctorAppointmentsTable = new javax.swing.JTable();
        pendingAppointmentsRadioButton = new javax.swing.JRadioButton();
        logoutButton = new javax.swing.JButton();
        prescriptionsPanel = new javax.swing.JPanel();
        patientSearchComboBox = new javax.swing.JComboBox<>();
        patientSearchLabel = new javax.swing.JLabel();
        diagnosisScrollPane = new javax.swing.JScrollPane();
        patientAppointmentsTable = new javax.swing.JTable();
        searchPatientAppointmentsButton = new javax.swing.JButton();
        doctorActionsPanel = new javax.swing.JPanel();
        doctorFirstnameLabel = new javax.swing.JLabel();
        doctorFirstnameField = new javax.swing.JTextField();
        doctorLastnameLabel = new javax.swing.JLabel();
        doctorLastnameField = new javax.swing.JTextField();
        doctorSpecialtyLabel = new javax.swing.JLabel();
        doctorLicenceLabel = new javax.swing.JLabel();
        doctorLicenceField = new javax.swing.JTextField();
        doctorOfficeLabel = new javax.swing.JLabel();
        doctorUsernameField = new javax.swing.JTextField();
        doctorUsernameLabel = new javax.swing.JLabel();
        doctorOfficeField = new javax.swing.JTextField();
        doctorPasswordField = new javax.swing.JTextField();
        doctorPasswordLabel = new javax.swing.JLabel();
        doctorConfirmPasswordLabel = new javax.swing.JLabel();
        doctorConfirmPasswordField = new javax.swing.JTextField();
        doctorSpecialtyComboBox = new javax.swing.JComboBox<>();
        saveDoctorButton = new javax.swing.JButton();
        doctorAppointmentsPanel = new javax.swing.JPanel();
        acceptAppointmentIdLabel = new javax.swing.JLabel();
        acceptAppointmentTitleLabel = new javax.swing.JLabel();
        requestedAppointmentComboBox = new javax.swing.JComboBox<>();
        doctorHeaderSeparator = new javax.swing.JSeparator();
        acceptAppointmentButton = new javax.swing.JButton();
        rescheduleAppointmentTitleLabel = new javax.swing.JLabel();
        rescheduleAppointmentIdLabel = new javax.swing.JLabel();
        rescheduleAppointmentComboBox = new javax.swing.JComboBox<>();
        rescheduleAppointmentButton = new javax.swing.JButton();
        rescheduleTimeLabel = new javax.swing.JLabel();
        rescheduleTimeField = new javax.swing.JTextField();
        rescheduleReasonLabel = new javax.swing.JLabel();
        rescheduleReasonField = new javax.swing.JTextField();
        doctorFormSeparator = new javax.swing.JSeparator();
        completeAppointmentTitleLabel = new javax.swing.JLabel();
        completeAppointmentIdLabel = new javax.swing.JLabel();
        completeAppointmentComboBox = new javax.swing.JComboBox<>();
        diagnosisLabel = new javax.swing.JLabel();
        appointmentObservationsLabel = new javax.swing.JLabel();
        recommendedTreatmentLabel = new javax.swing.JLabel();
        followUpLabel = new javax.swing.JLabel();
        completeAppointmentButton = new javax.swing.JButton();
        hospitalizationTitleLabel = new javax.swing.JLabel();
        hospitalizationReasonLabel = new javax.swing.JLabel();
        hospitalizationDateLabel = new javax.swing.JLabel();
        hospitalizationDateField = new javax.swing.JTextField();
        estimatedDurationLabel = new javax.swing.JLabel();
        estimatedDurationField = new javax.swing.JTextField();
        hospitalizationObservationsLabel = new javax.swing.JLabel();
        prescriptionTableScrollPane = new javax.swing.JScrollPane();
        hospitalizationObservationsArea = new javax.swing.JTextArea();
        generateHospitalizationButton = new javax.swing.JButton();
        hospitalizationActionComboBox = new javax.swing.JComboBox<>();
        hospitalizationRequestsRadioButton = new javax.swing.JRadioButton();
        hospitalizationPatientIdRadioButton = new javax.swing.JRadioButton();
        observationsScrollPane = new javax.swing.JScrollPane();
        diagnosisArea = new javax.swing.JTextArea();
        recommendedTreatmentScrollPane = new javax.swing.JScrollPane();
        appointmentObservationsArea = new javax.swing.JTextArea();
        followUpScrollPane = new javax.swing.JScrollPane();
        recommendedTreatmentArea = new javax.swing.JTextArea();
        hospitalizationReasonScrollPane = new javax.swing.JScrollPane();
        followUpArea = new javax.swing.JTextArea();
        prescriptionSeparator = new javax.swing.JSeparator();
        applyHospitalizationButton = new javax.swing.JButton();
        hospitalizationPatientComboBox = new javax.swing.JComboBox<>();
        hospitalizationObservationsScrollPane = new javax.swing.JScrollPane();
        hospitalizationReasonArea = new javax.swing.JTextArea();
        doctorProfilePanel = new javax.swing.JPanel();
        prescriptionAppointmentLabel = new javax.swing.JLabel();
        medicationNameLabel = new javax.swing.JLabel();
        medicationNameField = new javax.swing.JTextField();
        doseLabel = new javax.swing.JLabel();
        doseField = new javax.swing.JTextField();
        administrationRouteLabel = new javax.swing.JLabel();
        administrationRouteField = new javax.swing.JTextField();
        frequencyLabel = new javax.swing.JLabel();
        frequencyField = new javax.swing.JTextField();
        treatmentDurationLabel = new javax.swing.JLabel();
        treatmentDurationField = new javax.swing.JTextField();
        additionalInstructionsLabel = new javax.swing.JLabel();
        additionalInstructionsField = new javax.swing.JTextField();
        doctorAppointmentsScrollPane = new javax.swing.JScrollPane();
        prescriptionTable = new javax.swing.JTable();
        addPrescriptionButton = new javax.swing.JButton();
        prescriptionClearButton = new javax.swing.JButton();
        prescriptionAppointmentComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setRadius(50);

        titleBarPanel.setRadius(50);
        titleBarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarPanelMouseDragged(evt);
            }
        });
        titleBarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarPanelMousePressed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        closeButton.setText("X");
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        closeButton.setFocusable(false);
        closeButton.setRequestFocusEnabled(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        doctorViewTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        doctorViewTitleLabel.setText("DOCTOR VIEW");

        backToAdminButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        backToAdminButton.setText("Back");
        backToAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToAdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(titleBarPanel);
        titleBarPanel.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(doctorViewTitleLabel)
                .addGap(32, 32, 32)
                .addComponent(backToAdminButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doctorViewTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(backToAdminButton))
        );

        totalAppointmentsRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        totalAppointmentsRadioButton.setText("Total appointments");
        totalAppointmentsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAppointmentsRadioButtonActionPerformed(evt);
            }
        });

        doctorAppointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Patient", "Specialty", "Type", "Status"
            }
        ));
        patientAppointmentsScrollPane.setViewportView(doctorAppointmentsTable);

        pendingAppointmentsRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        pendingAppointmentsRadioButton.setText("Pending appointments");
        pendingAppointmentsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendingAppointmentsRadioButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(hospitalizationsPanel);
        hospitalizationsPanel.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutButton)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(totalAppointmentsRadioButton)
                            .addGap(18, 18, 18)
                            .addComponent(pendingAppointmentsRadioButton))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(patientAppointmentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalAppointmentsRadioButton)
                    .addComponent(pendingAppointmentsRadioButton))
                .addGap(18, 18, 18)
                .addComponent(patientAppointmentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(23, 23, 23))
        );

        doctorTabbedPane.addTab("Appointments visualization", hospitalizationsPanel);

        patientSearchComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientSearchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        patientSearchLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientSearchLabel.setText("Patient");

        patientAppointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        diagnosisScrollPane.setViewportView(patientAppointmentsTable);

        searchPatientAppointmentsButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        searchPatientAppointmentsButton.setText("Search");
        searchPatientAppointmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPatientAppointmentsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(prescriptionsPanel);
        prescriptionsPanel.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(patientSearchLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientSearchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(diagnosisScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchPatientAppointmentsButton)
                .addGap(601, 601, 601))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientSearchLabel)
                    .addComponent(patientSearchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(diagnosisScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(searchPatientAppointmentsButton)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        doctorTabbedPane.addTab("History Appointments of a patient", prescriptionsPanel);

        doctorFirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorFirstnameLabel.setText("Firstname");

        doctorFirstnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorLastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorLastnameLabel.setText("Lastname");

        doctorLastnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorSpecialtyLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorSpecialtyLabel.setText("Specialty");

        doctorLicenceLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorLicenceLabel.setText("License Number");

        doctorLicenceField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorOfficeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorOfficeLabel.setText("Assigned office");

        doctorUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctorUsernameLabel.setText("User");

        doctorOfficeField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctorPasswordLabel.setText("Password");

        doctorConfirmPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorConfirmPasswordLabel.setText("Password confirmation");

        doctorConfirmPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorSpecialtyComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorSpecialtyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        saveDoctorButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        saveDoctorButton.setText("Save");
        saveDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDoctorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(doctorActionsPanel);
        doctorActionsPanel.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(doctorFirstnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doctorFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doctorLastnameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(doctorLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doctorSpecialtyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(doctorSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(doctorLicenceLabel)
                        .addGap(18, 18, 18)
                        .addComponent(doctorLicenceField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doctorOfficeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doctorOfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(doctorUsernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(doctorUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(doctorPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(doctorConfirmPasswordLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(saveDoctorButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(561, 561, 561)
                        .addComponent(doctorConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorFirstnameLabel)
                    .addComponent(doctorFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorLastnameLabel)
                    .addComponent(doctorLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorSpecialtyLabel)
                    .addComponent(doctorSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorLicenceLabel)
                    .addComponent(doctorLicenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorOfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorOfficeLabel))
                .addGap(30, 30, 30)
                .addComponent(doctorUsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(doctorUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doctorPasswordLabel)
                .addGap(27, 27, 27)
                .addComponent(doctorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doctorConfirmPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(doctorConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(saveDoctorButton)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        doctorTabbedPane.addTab("Modify info", doctorActionsPanel);

        acceptAppointmentIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        acceptAppointmentIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceptAppointmentIdLabel.setText("Appointment ID");

        acceptAppointmentTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        acceptAppointmentTitleLabel.setText("Accept medical appointment");

        requestedAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        requestedAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        doctorHeaderSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        acceptAppointmentButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        acceptAppointmentButton.setText("Accept");
        acceptAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptAppointmentButtonActionPerformed(evt);
            }
        });

        rescheduleAppointmentTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rescheduleAppointmentTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rescheduleAppointmentTitleLabel.setText("Reschedule medical appointment");

        rescheduleAppointmentIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rescheduleAppointmentIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rescheduleAppointmentIdLabel.setText("Appointment");

        rescheduleAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rescheduleAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        rescheduleAppointmentButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rescheduleAppointmentButton.setText("Accept");
        rescheduleAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rescheduleAppointmentButtonActionPerformed(evt);
            }
        });

        rescheduleTimeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rescheduleTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rescheduleTimeLabel.setText("New time appointment");

        rescheduleTimeField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        rescheduleReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rescheduleReasonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rescheduleReasonLabel.setText("Reason for appointment");

        rescheduleReasonField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorFormSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        completeAppointmentTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        completeAppointmentTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completeAppointmentTitleLabel.setText("Complete medical appointment");

        completeAppointmentIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        completeAppointmentIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completeAppointmentIdLabel.setText("Appointment");

        completeAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        completeAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        diagnosisLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        diagnosisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diagnosisLabel.setText("Diagnosis");

        appointmentObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentObservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appointmentObservationsLabel.setText("Observations");

        recommendedTreatmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        recommendedTreatmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recommendedTreatmentLabel.setText("Recommended treatment");

        followUpLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        followUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        followUpLabel.setText("Follow-up indication");

        completeAppointmentButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        completeAppointmentButton.setText("Complete");
        completeAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeAppointmentButtonActionPerformed(evt);
            }
        });

        hospitalizationTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationTitleLabel.setText("Hospitalization");

        hospitalizationReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationReasonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationReasonLabel.setText("Reason for hospitalization");

        hospitalizationDateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationDateLabel.setText("Date of entry");

        hospitalizationDateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        estimatedDurationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        estimatedDurationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estimatedDurationLabel.setText("Estimated duration");

        estimatedDurationField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        hospitalizationObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationObservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationObservationsLabel.setText("Observations");

        hospitalizationObservationsArea.setColumns(20);
        hospitalizationObservationsArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationObservationsArea.setRows(5);
        prescriptionTableScrollPane.setViewportView(hospitalizationObservationsArea);

        generateHospitalizationButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        generateHospitalizationButton.setText("Generate");
        generateHospitalizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateHospitalizationButtonActionPerformed(evt);
            }
        });

        hospitalizationActionComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationActionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        hospitalizationRequestsRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationRequestsRadioButton.setText("Requests");

        hospitalizationPatientIdRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationPatientIdRadioButton.setText("Patient ID");

        diagnosisArea.setColumns(20);
        diagnosisArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        diagnosisArea.setRows(5);
        observationsScrollPane.setViewportView(diagnosisArea);

        appointmentObservationsArea.setColumns(20);
        appointmentObservationsArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentObservationsArea.setRows(5);
        recommendedTreatmentScrollPane.setViewportView(appointmentObservationsArea);

        recommendedTreatmentArea.setColumns(20);
        recommendedTreatmentArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        recommendedTreatmentArea.setRows(5);
        followUpScrollPane.setViewportView(recommendedTreatmentArea);

        followUpArea.setColumns(20);
        followUpArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        followUpArea.setRows(5);
        hospitalizationReasonScrollPane.setViewportView(followUpArea);

        prescriptionSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        applyHospitalizationButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        applyHospitalizationButton.setText("Cancel");
        applyHospitalizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyHospitalizationButtonActionPerformed(evt);
            }
        });

        hospitalizationPatientComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationPatientComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        hospitalizationReasonArea.setColumns(20);
        hospitalizationReasonArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationReasonArea.setRows(5);
        hospitalizationObservationsScrollPane.setViewportView(hospitalizationReasonArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(doctorAppointmentsPanel);
        doctorAppointmentsPanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(acceptAppointmentButton)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(requestedAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67))))
                            .addComponent(acceptAppointmentIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(doctorHeaderSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(acceptAppointmentTitleLabel)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rescheduleAppointmentTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rescheduleAppointmentIdLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rescheduleTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rescheduleReasonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(rescheduleAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(rescheduleTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(rescheduleReasonField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(rescheduleAppointmentButton)))
                            .addGap(91, 91, 91))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doctorFormSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(completeAppointmentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(completeAppointmentIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(completeAppointmentTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(completeAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diagnosisLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(appointmentObservationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(followUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(recommendedTreatmentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(observationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(recommendedTreatmentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(followUpScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(hospitalizationReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(prescriptionSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hospitalizationTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hospitalizationDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(estimatedDurationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hospitalizationObservationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hospitalizationDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estimatedDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(applyHospitalizationButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(generateHospitalizationButton))
                            .addComponent(prescriptionTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(hospitalizationActionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(hospitalizationRequestsRadioButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(hospitalizationPatientIdRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(hospitalizationPatientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hospitalizationReasonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hospitalizationObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctorHeaderSeparator)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorFormSeparator)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(completeAppointmentTitleLabel)
                        .addGap(10, 10, 10)
                        .addComponent(completeAppointmentIdLabel)
                        .addGap(18, 18, 18)
                        .addComponent(completeAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diagnosisLabel)
                        .addGap(18, 18, 18)
                        .addComponent(observationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(appointmentObservationsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(recommendedTreatmentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(recommendedTreatmentLabel)
                        .addGap(18, 18, 18)
                        .addComponent(followUpScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(followUpLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hospitalizationReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(completeAppointmentButton)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(acceptAppointmentTitleLabel)
                                .addGap(18, 18, 18)
                                .addComponent(acceptAppointmentIdLabel)
                                .addGap(18, 18, 18)
                                .addComponent(requestedAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(acceptAppointmentButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(rescheduleAppointmentTitleLabel)
                                .addGap(18, 18, 18)
                                .addComponent(rescheduleAppointmentIdLabel)
                                .addGap(18, 18, 18)
                                .addComponent(rescheduleAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rescheduleTimeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(rescheduleTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rescheduleReasonLabel)
                                .addGap(18, 18, 18)
                                .addComponent(rescheduleReasonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(rescheduleAppointmentButton)))
                        .addGap(18, 18, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(hospitalizationTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalizationRequestsRadioButton)
                    .addComponent(hospitalizationPatientIdRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalizationActionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalizationPatientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(hospitalizationReasonLabel)
                .addGap(16, 16, 16)
                .addComponent(hospitalizationObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospitalizationDateLabel)
                .addGap(18, 18, 18)
                .addComponent(hospitalizationDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(estimatedDurationLabel)
                .addGap(18, 18, 18)
                .addComponent(estimatedDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hospitalizationObservationsLabel)
                .addGap(18, 18, 18)
                .addComponent(prescriptionTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateHospitalizationButton)
                    .addComponent(applyHospitalizationButton))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(prescriptionSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        doctorTabbedPane.addTab("Request/Appointments", doctorAppointmentsPanel);

        prescriptionAppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        prescriptionAppointmentLabel.setText("Appointment ID");

        medicationNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        medicationNameLabel.setText("Medication name");

        medicationNameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doseLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doseLabel.setText("Dose");

        doseField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        administrationRouteLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        administrationRouteLabel.setText("Administration route");

        administrationRouteField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        frequencyLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        frequencyLabel.setText("Frecuency");

        frequencyField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        treatmentDurationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        treatmentDurationLabel.setText("Treatment duration");

        treatmentDurationField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        additionalInstructionsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        additionalInstructionsLabel.setText("Additional instructions");

        additionalInstructionsField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        prescriptionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Medication name", "Dose", "Administration route", "Treatment duration", "Additional instructions", "Frecuency"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doctorAppointmentsScrollPane.setViewportView(prescriptionTable);

        addPrescriptionButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        addPrescriptionButton.setText("Add");
        addPrescriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPrescriptionButtonActionPerformed(evt);
            }
        });

        prescriptionClearButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        prescriptionClearButton.setText("Prescribe");
        prescriptionClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescriptionClearButtonActionPerformed(evt);
            }
        });

        prescriptionAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        prescriptionAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(doctorProfilePanel);
        doctorProfilePanel.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(doctorAppointmentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(prescriptionAppointmentLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(prescriptionAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(medicationNameLabel))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(treatmentDurationLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(treatmentDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(additionalInstructionsLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(additionalInstructionsField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(frequencyLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(frequencyField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(medicationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(doseLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(doseField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(administrationRouteLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(administrationRouteField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addPrescriptionButton))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(583, 583, 583)
                        .addComponent(prescriptionClearButton)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prescriptionAppointmentLabel)
                    .addComponent(medicationNameLabel)
                    .addComponent(medicationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doseLabel)
                    .addComponent(doseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(administrationRouteLabel)
                    .addComponent(administrationRouteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPrescriptionButton)
                    .addComponent(prescriptionAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(treatmentDurationLabel)
                    .addComponent(treatmentDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(additionalInstructionsLabel)
                    .addComponent(additionalInstructionsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frequencyLabel)
                    .addComponent(frequencyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(doctorAppointmentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(prescriptionClearButton)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        doctorTabbedPane.addTab("Prescribe medications", doctorProfilePanel);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doctorTabbedPane))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(titleBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doctorTabbedPane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleBarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void titleBarPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pendingAppointmentsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        totalAppointmentsRadioButton.setSelected(false);
        loadDoctorAppointmentTable(true);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void saveDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ControllerResponse response = doctorController.updateDoctor(
                String.valueOf(doctor.getId()),
                doctorFirstnameField.getText(),
                doctorLastnameField.getText(),
                String.valueOf(doctorSpecialtyComboBox.getSelectedItem()),
                doctorLicenceField.getText(),
                doctorOfficeField.getText(),
                doctorUsernameField.getText(),
                doctorPasswordField.getText(),
                doctorConfirmPasswordField.getText()
        );

        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            this.doctor = (Doctor) userRepository.findById(doctor.getId());
            loadDoctorData();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        NewJFrame login = new NewJFrame();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void backToAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        NewJFrame11 admin = new NewJFrame11(user,users,hospitalizations, appointments);
        this.setVisible(false);
        admin.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void applyHospitalizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        ControllerResponse response;
        if (hospitalizationRequestsRadioButton.isSelected()) {
            response = ospedaleFacade.approveHospitalization(String.valueOf(hospitalizationActionComboBox.getSelectedItem()));
        } else {
            response = ospedaleFacade.cancelHospitalization(String.valueOf(hospitalizationActionComboBox.getSelectedItem()));
        }
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            loadDoctorCombos();
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void generateHospitalizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ControllerResponse response = ospedaleFacade.requestHospitalization(
                String.valueOf(hospitalizationPatientComboBox.getSelectedItem()),
                String.valueOf(doctor.getId()),
                hospitalizationDateField.getText(),
                hospitalizationReasonArea.getText(),
                RoomType.IMC.name(),
                hospitalizationObservationsArea.getText()
        );

        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            loadDoctorCombos();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void searchPatientAppointmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Patient selectedPatient = findPatient(String.valueOf(patientSearchComboBox.getSelectedItem()));
        DefaultTableModel model = (DefaultTableModel) patientAppointmentsTable.getModel();
        model.setRowCount(0);
        if (selectedPatient == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un paciente");
            return;
        }
        for (Appointment a : appointmentRepository.findByPatientId(selectedPatient.getId())) {
            model.addRow(new Object[]{a.getId(), a.getDatetime().toString(), a.getDoctor().getFirstname() + " " + a.getDoctor().getLastname(), a.getSpecialty().name(), a.isType() ? "In-person" : "Remote", a.getStatus().name()});
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void totalAppointmentsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        pendingAppointmentsRadioButton.setSelected(false);
        loadDoctorAppointmentTable(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void acceptAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ControllerResponse response = ospedaleFacade.acceptAppointment(String.valueOf(requestedAppointmentComboBox.getSelectedItem()));
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            loadDoctorCombos();
            loadDoctorAppointmentTable(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void completeAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String appointmentId = String.valueOf(completeAppointmentComboBox.getSelectedItem());
        Appointment appointment = appointmentRepository.findById(appointmentId);
        int option = JOptionPane.showConfirmDialog(this, "Hospitalizar paciente desde esta cita?", "Hospitalizacion", JOptionPane.YES_NO_OPTION);
        ControllerResponse response;

        if (option == JOptionPane.YES_OPTION) {
            response = ospedaleFacade.hospitalizeFromAppointment(
                    appointment,
                    recommendedTreatmentArea.getText(),
                    RoomType.IMC.name(),
                    appointmentObservationsArea.getText()
            );
        } else {
            response = ospedaleFacade.completeAppointment(
                    appointmentId,
                    diagnosisArea.getText(),
                    appointmentObservationsArea.getText(),
                    recommendedTreatmentArea.getText(),
                    followUpArea.getText()
            );
        }

        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            loadDoctorCombos();
            loadDoctorAppointmentTable(false);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void prescriptionClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        DefaultTableModel model = (DefaultTableModel) prescriptionTable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void addPrescriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        DefaultTableModel model = (DefaultTableModel) prescriptionTable.getModel();
        
        String appointmentId = prescriptionAppointmentComboBox.getItemAt(prescriptionAppointmentComboBox.getSelectedIndex());
        String medicationName = medicationNameField.getText();
        String administrationRoute = administrationRouteField.getText();
        String aditionalIformation = additionalInstructionsField.getText();
        Appointment appointment = appointmentRepository.findById(appointmentId);

        ControllerResponse response = ospedaleFacade.prescribeMedication(
                appointment,
                medicationName,
                doseField.getText(),
                administrationRoute,
                treatmentDurationField.getText(),
                frequencyField.getText(),
                aditionalIformation
        );

        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            model.addRow(new Object[]{appointmentId, medicationName, doseField.getText(), administrationRoute, treatmentDurationField.getText(), aditionalIformation, frequencyField.getText()});
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void rescheduleAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ControllerResponse response = ospedaleFacade.rescheduleAppointment(
                String.valueOf(rescheduleAppointmentComboBox.getSelectedItem()),
                rescheduleTimeField.getText(),
                rescheduleReasonField.getText()
        );

        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            loadDoctorCombos();
            loadDoctorAppointmentTable(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void loadDoctorCombos() {
        requestedAppointmentComboBox.removeAllItems();
        rescheduleAppointmentComboBox.removeAllItems();
        completeAppointmentComboBox.removeAllItems();
        prescriptionAppointmentComboBox.removeAllItems();
        patientSearchComboBox.removeAllItems();
        hospitalizationActionComboBox.removeAllItems();
        hospitalizationPatientComboBox.removeAllItems();

        requestedAppointmentComboBox.addItem("Select one");
        rescheduleAppointmentComboBox.addItem("Select one");
        completeAppointmentComboBox.addItem("Select one");
        prescriptionAppointmentComboBox.addItem("Select one");
        patientSearchComboBox.addItem("Select one");
        hospitalizationActionComboBox.addItem("Select one");
        hospitalizationPatientComboBox.addItem("Select one");

        for (Appointment appointment : appointmentRepository.findByDoctorId(doctor.getId())) {
            if (appointment.getStatus() == AppointmentStatus.REQUESTED) {
                requestedAppointmentComboBox.addItem(appointment.getId());
            }
            if (appointment.getStatus() == AppointmentStatus.PENDING) {
                rescheduleAppointmentComboBox.addItem(appointment.getId());
                completeAppointmentComboBox.addItem(appointment.getId());
                prescriptionAppointmentComboBox.addItem(appointment.getId());
            }
        }

        for (User currentUser : users) {
            if (currentUser instanceof Patient) {
                patientSearchComboBox.addItem(String.valueOf(currentUser.getId()));
                hospitalizationPatientComboBox.addItem(String.valueOf(currentUser.getId()));
            }
        }

        for (Hospitalization hospitalization : hospitalizations) {
            if (hospitalization.getDoctor().getId() == doctor.getId()
                    && hospitalization.getStatus() != HospitalizationStatus.CANCELED
                    && (!hospitalizationRequestsRadioButton.isSelected() || hospitalization.getStatus() == HospitalizationStatus.REQUESTED)) {
                hospitalizationActionComboBox.addItem(hospitalization.getId());
            }
        }
    }

    private void loadDoctorData() {
        doctorFirstnameField.setText(doctor.getFirstname());
        doctorLastnameField.setText(doctor.getLastname());
        selectDoctorSpecialty();
        doctorLicenceField.setText(doctor.getLicenceNumber());
        doctorOfficeField.setText(doctor.getAssignedOffice());
        doctorUsernameField.setText(doctor.getUsername());
        doctorPasswordField.setText(doctor.getPassword());
        doctorConfirmPasswordField.setText(doctor.getPassword());
    }

    private void selectDoctorSpecialty() {
        for (int i = 0; i < doctorSpecialtyComboBox.getItemCount(); i++) {
            String item = doctorSpecialtyComboBox.getItemAt(i);
            try {
                if (Specialty.fromDisplayString(item) == doctor.getSpecialty()) {
                    doctorSpecialtyComboBox.setSelectedIndex(i);
                    return;
                }
            } catch (Exception e) {
            }
        }
    }

    private void loadDoctorAppointmentTable(boolean onlyPending) {
        ControllerResponse response = appointmentController.listDoctorAppointments(String.valueOf(doctor.getId()));
        DefaultTableModel model = (DefaultTableModel) doctorAppointmentsTable.getModel();
        model.setRowCount(0);
        if (!response.isOk()) {
            return;
        }

        JSONArray array = new JSONArray(response.getData());
        for (int i = 0; i < array.length(); i++) {
            JSONObject item = array.getJSONObject(i);
            if (!onlyPending || item.getString("status").equals(AppointmentStatus.PENDING.name())) {
                model.addRow(new Object[]{
                    item.getString("id"),
                    item.getString("datetime"),
                    item.getString("patientName"),
                    item.getString("specialty"),
                    item.getString("type"),
                    item.getString("status")
                });
            }
        }
    }

    private Patient findPatient(String idText) {
        try {
            User selectedUser = userRepository.findById(Long.parseLong(idText));
            if (selectedUser instanceof Patient) {
                return (Patient) selectedUser;
            }
            return null;
        } catch (Exception e) {
            return null;
        }
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton prescriptionClearButton;
    private javax.swing.JButton backToAdminButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton applyHospitalizationButton;
    private javax.swing.JButton acceptAppointmentButton;
    private javax.swing.JButton rescheduleAppointmentButton;
    private javax.swing.JButton completeAppointmentButton;
    private javax.swing.JButton generateHospitalizationButton;
    private javax.swing.JButton addPrescriptionButton;
    private javax.swing.JButton searchPatientAppointmentsButton;
    private javax.swing.JButton saveDoctorButton;
    private javax.swing.JComboBox<String> doctorSpecialtyComboBox;
    private javax.swing.JComboBox<String> requestedAppointmentComboBox;
    private javax.swing.JComboBox<String> rescheduleAppointmentComboBox;
    private javax.swing.JComboBox<String> completeAppointmentComboBox;
    private javax.swing.JComboBox<String> patientSearchComboBox;
    private javax.swing.JComboBox<String> hospitalizationActionComboBox;
    private javax.swing.JComboBox<String> prescriptionAppointmentComboBox;
    private javax.swing.JComboBox<String> hospitalizationPatientComboBox;
    private javax.swing.JLabel doctorViewTitleLabel;
    private javax.swing.JLabel doctorPasswordLabel;
    private javax.swing.JLabel doctorConfirmPasswordLabel;
    private javax.swing.JLabel acceptAppointmentTitleLabel;
    private javax.swing.JLabel acceptAppointmentIdLabel;
    private javax.swing.JLabel rescheduleAppointmentTitleLabel;
    private javax.swing.JLabel rescheduleAppointmentIdLabel;
    private javax.swing.JLabel rescheduleTimeLabel;
    private javax.swing.JLabel rescheduleReasonLabel;
    private javax.swing.JLabel completeAppointmentTitleLabel;
    private javax.swing.JLabel doctorFirstnameLabel;
    private javax.swing.JLabel completeAppointmentIdLabel;
    private javax.swing.JLabel diagnosisLabel;
    private javax.swing.JLabel appointmentObservationsLabel;
    private javax.swing.JLabel recommendedTreatmentLabel;
    private javax.swing.JLabel followUpLabel;
    private javax.swing.JLabel hospitalizationTitleLabel;
    private javax.swing.JLabel hospitalizationReasonLabel;
    private javax.swing.JLabel hospitalizationDateLabel;
    private javax.swing.JLabel estimatedDurationLabel;
    private javax.swing.JLabel doctorLastnameLabel;
    private javax.swing.JLabel hospitalizationObservationsLabel;
    private javax.swing.JLabel prescriptionAppointmentLabel;
    private javax.swing.JLabel medicationNameLabel;
    private javax.swing.JLabel doseLabel;
    private javax.swing.JLabel administrationRouteLabel;
    private javax.swing.JLabel frequencyLabel;
    private javax.swing.JLabel treatmentDurationLabel;
    private javax.swing.JLabel additionalInstructionsLabel;
    private javax.swing.JLabel patientSearchLabel;
    private javax.swing.JLabel doctorSpecialtyLabel;
    private javax.swing.JLabel doctorLicenceLabel;
    private javax.swing.JLabel doctorOfficeLabel;
    private javax.swing.JLabel doctorUsernameLabel;
    private javax.swing.JPanel doctorAppointmentsPanel;
    private javax.swing.JPanel doctorProfilePanel;
    private javax.swing.JPanel doctorActionsPanel;
    private javax.swing.JPanel hospitalizationsPanel;
    private javax.swing.JPanel prescriptionsPanel;
    private javax.swing.JRadioButton totalAppointmentsRadioButton;
    private javax.swing.JRadioButton pendingAppointmentsRadioButton;
    private javax.swing.JRadioButton hospitalizationRequestsRadioButton;
    private javax.swing.JRadioButton hospitalizationPatientIdRadioButton;
    private javax.swing.JScrollPane prescriptionTableScrollPane;
    private javax.swing.JScrollPane hospitalizationObservationsScrollPane;
    private javax.swing.JScrollPane doctorAppointmentsScrollPane;
    private javax.swing.JScrollPane patientAppointmentsScrollPane;
    private javax.swing.JScrollPane diagnosisScrollPane;
    private javax.swing.JScrollPane observationsScrollPane;
    private javax.swing.JScrollPane recommendedTreatmentScrollPane;
    private javax.swing.JScrollPane followUpScrollPane;
    private javax.swing.JScrollPane hospitalizationReasonScrollPane;
    private javax.swing.JSeparator doctorHeaderSeparator;
    private javax.swing.JSeparator doctorFormSeparator;
    private javax.swing.JSeparator prescriptionSeparator;
    private javax.swing.JTabbedPane doctorTabbedPane;
    private javax.swing.JTable prescriptionTable;
    private javax.swing.JTable doctorAppointmentsTable;
    private javax.swing.JTable patientAppointmentsTable;
    private javax.swing.JTextArea hospitalizationObservationsArea;
    private javax.swing.JTextArea diagnosisArea;
    private javax.swing.JTextArea appointmentObservationsArea;
    private javax.swing.JTextArea recommendedTreatmentArea;
    private javax.swing.JTextArea followUpArea;
    private javax.swing.JTextArea hospitalizationReasonArea;
    private javax.swing.JTextField doctorFirstnameField;
    private javax.swing.JTextField doctorConfirmPasswordField;
    private javax.swing.JTextField rescheduleTimeField;
    private javax.swing.JTextField rescheduleReasonField;
    private javax.swing.JTextField doctorLastnameField;
    private javax.swing.JTextField hospitalizationDateField;
    private javax.swing.JTextField estimatedDurationField;
    private javax.swing.JTextField medicationNameField;
    private javax.swing.JTextField doseField;
    private javax.swing.JTextField administrationRouteField;
    private javax.swing.JTextField frequencyField;
    private javax.swing.JTextField treatmentDurationField;
    private javax.swing.JTextField additionalInstructionsField;
    private javax.swing.JTextField doctorLicenceField;
    private javax.swing.JTextField doctorUsernameField;
    private javax.swing.JTextField doctorOfficeField;
    private javax.swing.JTextField doctorPasswordField;
    private packagee.PanelRound mainPanel;
    private packagee.PanelRound titleBarPanel;
    // End of variables declaration//GEN-END:variables
}
